[general]
temp_files_save_location = "BrokenCreated"
found_broken_files_save_location = "BrokenFound"
image_size = 1
number_generated_svg = 100
max_number_of_operators = 500
max_number_of_arguments = 20
generate_invalid_items = false
timeout_seconds = 5
debug_printing_non_broken = false
timeout_entire_process = 14400


svg_tool_path = "./thorvg/build/src/tools/svg2png/svg2png"
arguments = "{FILE} -r {SIZE}x{SIZE}"
#svg_tool_path = "resvg"
#arguments = "{FILE} -w {SIZE} -h {SIZE}"
#svg_tool_path = "inkscape"
#arguments = "{FILE} --export-type=png -w {SIZE} -h {SIZE}"
#svg_tool_path = "rsvg-convert"
#arguments = "{FILE} -w {SIZE} -h {SIZE}"