[general]
temp_files_save_location = "/home/rafal/Desktop/SVG/BrokenCreated"
found_broken_files_save_location = "/home/rafal/Desktop/SVG/BrokenFound"
image_size = 1
number_generated_svg = 20000
max_number_of_operators = 10
max_number_of_arguments = 15
generate_invalid_items = false
timeout_seconds = 5
debug_printing_non_broken = false



svg_tool_path = "/home/rafal/test/thorvg/build/src/bin/svg2png/svg2png"
arguments = "{FILE} -r {SIZE}x{SIZE}"
#svg_tool_path = "resvg"
#arguments = "{FILE} -w {SIZE} -h {SIZE}"
#svg_tool_path = "inkscape"
#arguments = "{FILE} --export-type=png -w {SIZE} -h {SIZE}"
#svg_tool_path = "rsvg-convert"
#arguments = "{FILE} -w {SIZE} -h {SIZE}"